# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zneOeeLv_yVN2e1Irx0mqf52M3G2W9ZB
"""

# 📟 Simple Calculator by Iqra

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "❌ Cannot divide by zero!"

# Menu
print("📱 Welcome to Iqra's Calculator")
print("Choose an operation:")
print("1 ➕ Add")
print("2 ➖ Subtract")
print("3 ✖️ Multiply")
print("4 ➗ Divide")

# Get user choice
choice = input("Enter choice (1/2/3/4): ")

# Get numbers
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

# Perform operation
if choice == '1':
    print(f"Result: {add(num1, num2)}")
elif choice == '2':
    print(f"Result: {subtract(num1, num2)}")
elif choice == '3':
    print(f"Result: {multiply(num1, num2)}")
elif choice == '4':
    print(f"Result: {divide(num1, num2)}")
else:
    print("⚠️ Invalid input. Please select 1, 2, 3 or 4.")