# -*- coding: utf-8 -*-
"""Iqra's birthday countdown2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zn7qFQrJUMLY0-zk8Y9UUiMvp4tQuf5g
"""

#Import libraries
import time
from datetime import datetime

#Set Iqra's Bday
birthday_date = datetime(2025, 12, 10)

#Bday message
print("🎉 Countdown to Iqra's Birthday Begins! 🎂🎈")

#Countdown loop
while True:
    now = datetime.now()
    remaining_time = birthday_date - now

    if remaining_time.total_seconds() <= 0:
        print("\n🎊🎂🎁 Happy Birthday IQRA! 💖💫")
        break

#Calculate remaining days, hours, minutes, seconds
    days = remaining_time.days
    hours, remainder = divmod(remaining_time.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    print(f"⏳ {days}d {hours}h {minutes}m {seconds}s until Iqra's BIG DAY! 🎈", end="\r")
    time.sleep(1)