# -*- coding: utf-8 -*-
"""Rock,paper,scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrzrJa9_zPIQCXNKd2Y-nHkT-aC_mnH6
"""

import random

players = ["Anita", "Iqra", "Archu"]
choices = ["rock", "paper", "scissors"]

print("🎉 Welcome to Rock, Paper, Scissors!")
print("👯 Let's play a game between Anita, Iqra, and Archu!")

# Each player makes a random choice
moves = {}
for player in players:
    move = random.choice(choices)
    moves[player] = move
    print(f"🎲 {player} chooses: {move.capitalize()}")

# Function to determine the winner
def determine_winner(moves):
    unique_moves = set(moves.values())

    if len(unique_moves) == 1:
        return "😅 It's a tie! All chose the same!"

    if "rock" in unique_moves and "scissors" in unique_moves and "paper" in unique_moves:
        return "🤯 It's a chaotic tie! Everyone counters someone!"

    winner = None
    if "rock" in unique_moves and "scissors" in unique_moves:
        winner = [name for name, move in moves.items() if move == "rock"]
    elif "scissors" in unique_moves and "paper" in unique_moves:
        winner = [name for name, move in moves.items() if move == "scissors"]
    elif "paper" in unique_moves and "rock" in unique_moves:
        winner = [name for name, move in moves.items() if move == "paper"]

    if winner:
        if len(winner) == 1:
            return f"🏆 {winner[0]} wins the round! 🎉"
        else:
            return f"😎 It's a tie between: {', '.join(winner)}"
    else:
        return "🤔 Unexpected outcome!"

# Show the result
print("\n📣 Result:")
print(determine_winner(moves))